version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: docker-config/rest.Dockerfile
    links:
      - db
      - msg
    deploy:
      replicas: 3
    environment:
      DEALS_DB_URL: mongodb://db:27017/deal
      USERS_DB_URL: mongodb://db:27017/user
      REDIS_URL: redis://msg:6379
      REDIS_HOST: msg
  engine:
    build:
      context: .
      dockerfile: docker-config/engine.Dockerfile
    links:
      - db
      - msg
    environment:
      DEALS_DB_URL: mongodb://db:27017/deal
      REDIS_URL: redis://msg:6379
      REDIS_HOST: msg
  socket:
    build:
      context: .
      dockerfile: docker-config/socket.Dockerfile
    links:
      - msg
    deploy:
      replicas: 3
    environment:
      REDIS_URL: redis://msg:6379
  reporting:
    build:
      context: .
      dockerfile: docker-config/reporting.Dockerfile
    links:
      - db
      - msg
    environment:
      REDIS_URL: redis://msg:6379
      REPORTING_DB_URL: mongodb://db:27017/report
  nginx:
    image: nginx:1.16.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rest
    ports:
      - '3000:3000'
      - '8080:8080'
  db:
    image: mongo:3
  msg:
    image: redis:4.0-alpine
