name: Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 4

      - name: Integration Testing
        run: yarn test:e2e

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
